[package]
name = "cep47-logic"
version = "0.1.0"
authors = ["Maciej Zielinski <maciek.s.zielinski@gmail.com>"]
edition = "2018"

[dependencies]
casper-types = { git = "https://github.com/casper-network/casper-node", branch = "dev"}

[dev-dependencies]
rand = "0.7.3"
maplit = "1.0.2"