[package]
name = "dragons-nft"
version = "0.1.0"
authors = ["astro019 <dmitry.yakov7@gmail.com>"]
edition = "2018"

[dependencies]
casper-contract = { git = "https://github.com/casper-network/casper-node/smart_contracts/contract", rev = "77bd1af9ed21a52b8ec6d2804195d5413c9f3ea1"} #{ path = "../../casper-node/smart_contracts/contract"}
casper-types = { git = "https://github.com/casper-network/casper-node/types", rev = "77bd1af9ed21a52b8ec6d2804195d5413c9f3ea1"}#{ path = "../../casper-node/types"}
cep47 = { path="../cep47", features = ["no_owner_of"]}

[[bin]]
name = "dragons-nft"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
default = ["casper-contract/std", "casper-types/std"]

